### ISSUE TITLE
Bad version numbers in igloo-dependency-* poms

### ISSUE THREAD

**Issue by rjoly** [igloo-project/igloo-parent#15]
# Statement

In `igloo-parent-maven-configuration-core/pom.xml`:
- version of `igloo-dependency-hibernate-search` dependency uses `${project.version}` which:
  - seems to be logical
  - **BUT** is badly interpreted while processing build of a client project 
- version of `igloo-dependency-test` and `igloo-dependency-elasticsearch-test` dependencies use Igloo's version as a static string (currently `1.1.0`) which:
  - doesn't seem to be a good practice
  - **BUT** seems to be correctly updated while performing Igloo releases

Additionally, we can find other inconsistencies in `igloo-dependency-*` modules:
- `igloo-dependency-core-spring/pom.xml` -> `${project.version}` used for `igloo-dependency-core-logging`
- `igloo-dependency-core-spring-security/pom.xml` -> `${project.version}` used for `igloo-dependency-core-spring`
- `igloo-dependency-hibernate-core/pom.xml` -> static string (`1.1.0`) used for `igloo-dependency-core-logging`
- `igloo-dependency-hibernate-search/pom.xml` 
  - static string (`1.1.0`) used for `igloo-dependency-hibernate-core`
  - `${project.version}` used for `igloo-dependency-core-logging`
- `igloo-dependency-less4j/pom.xml` -> `${project.version}` used for `igloo-dependency-core-logging`

In `igloo-component-*` and `igloo-package-*` modules, `${project.version}` is mostly used, except (search for "1.1.0" in "pom.xml" files to reproduce, few false positives):
- `igloo-component-jpa-externallinkchecker/pom.xml` -> static string (`1.1.0`) used for `igloo-component-jpa-test`
- `igloo-component-jpa-security/pom.xml` -> static string (`1.1.0`) used for `igloo-component-jpa-test`
- `igloo-component-rest-jersey2/pom.xml` -> static string (`1.1.0`) used for `igloo-component-jpa-test`
- `igloo-component-wicket-more/pom.xml` -> static string (`1.1.0`) used for `igloo-component-jpa-test`

# Issue on client project

The version of `igloo-dependency-hibernate-search` dependency, using `${project.version}`, is badly interpreted while processing build of a client project. The version number used in this case is the client project's version instead of Igloo's version.

But, with a kind of magic, dependencies are not broken and the build run correctly...

**Comment by lalmeras** [comment]
Issue for releasing with jgitflow is fixed in v1.1.3 https://igloo-doc.readthedocs.io/en/latest/release-notes/1.x.html#id2
