### ISSUE TITLE
Move from truezip to trueVFS ?

### ISSUE THREAD

**Issue by lalmeras** [igloo-project/igloo-parent#6]
truezip is in maintenance mode ; it is working fine, but we should consider migrating on another solution.

Candidates:

* trueVFS: http://truevfs.net/

Note about truezip sources:

``` bash
hg clone https://bitbucket.org/christian-schlichtherle/truezip7
hg checkout 6247:a92842c1275b
```

**Comment by MargotPiva** [comment]
Released in v3.0.0
