### ISSUE TITLE
StorageConsistencyCheck#checkType not set

### ISSUE THREAD

**Issue by lalmeras** [igloo-project/igloo-parent#66]
Entity field `StorageConsistencyCheck#checkType` is not set when storage consistency is computed.

Missing `setCheckType` call is surely here : `org.igloo.storage.impl.StorageService.checkConsistency(StorageUnit, boolean)`

Rework `TestConsistency` to check that `setCheckType` is called with the expected value, then fix the issue.

**Impact analysis:**
* checkType is null on performed analysis
* so unit is always considered as not checked, and so is eligible for a check
* if checksum check is enabled, then checksum check is performed at each run

When fixed, new consistency checks will be correctly set, and consistency check normal behavior must be restored.

**Comment by MargotPiva** [comment]
Problem will be solved in 4.2.0 release.

**Comment by lalmeras** [comment]
Released in 4.2.0.
